[workspace.dependencies]
once_cell = "1.19"
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.10"
serde = { version = "1.0.219", features = ["derive"] }
syn = { version = "2.0", features = ["full", "parsing", "extra-traits"] }
thiserror = "1.0"


[workspace]
members = ["crates/*"]
