[package]
name = "to_python"
version = "0.1.0"
edition = "2021"
authors = ["nobane"]
license = "MIT"

[dependencies]
__internals = { path = "../internals" }

once_cell = { workspace = true }
thiserror = { workspace = true }
serde ={ workspace = true }
